#!/usr/bin/env bash
# codex_bridge.sh — opt-in LiteLLM bridge that lets codex talk to
# OpenAI-compatible chat-completions providers (MiniMax, OpenRouter,
# Together, Groq, etc.) by translating its Responses-API requests on
# the fly. Sourced by start.sh (Docker boot) and install.sh's runtime
# helper (bare-host boot) so both paths get the same shape.
#
# Why this exists: codex 0.72's `wire_api` only supports `responses`
# (verified against codex-rs/model-provider-info — see PR #10 desc).
# Without this bridge, the codex template requires a real OpenAI key
# and silently fails 401 against any other provider. The bridge runs
# litellm proxy on 127.0.0.1:4000, points codex at it via a custom
# `model_providers` entry, and codex thinks it's hitting OpenAI.
#
# Activation rule: bridge starts ONLY when a non-OpenAI provider key
# is present (currently MINIMAX_API_KEY; extend the case statement
# below for other providers). When the user has OPENAI_API_KEY only,
# this script is a no-op so we don't pay the litellm boot cost.

set -euo pipefail

# Default off; set to "1" if a supported alternate provider is present.
BRIDGE_ENABLED=0
BRIDGE_PROVIDER=""
BRIDGE_MODEL=""

if [ -n "${MINIMAX_API_KEY:-}" ]; then
  BRIDGE_ENABLED=1
  BRIDGE_PROVIDER="minimax"
  # MiniMax model id surfaced as the codex `model` field. Pin to the
  # default MiniMax-M2 family — the canvas Provider dropdown still
  # lets the operator override per-workspace via runtime_config.model,
  # but that override has to be one MiniMax knows about.
  BRIDGE_MODEL="${CODEX_BRIDGE_MODEL:-MiniMax-M2}"
fi

if [ "$BRIDGE_ENABLED" != "1" ]; then
  echo "[codex_bridge] no alternate-provider key set — bridge disabled, codex will use OpenAI direct"
  return 0 2>/dev/null || exit 0
fi

echo "[codex_bridge] activating ${BRIDGE_PROVIDER} bridge (model=${BRIDGE_MODEL})"

# ---- 1. litellm proxy config ----------------------------------------
# Single model entry. The `codex-bridge` model name is what codex sends
# in the request body; LiteLLM routes it through its native MiniMax
# provider which speaks /v1/chat/completions and translates back to
# the Responses-shaped reply codex expects.
LITELLM_CONFIG="${LITELLM_CONFIG:-/tmp/litellm-codex.yaml}"
case "$BRIDGE_PROVIDER" in
  minimax)
    cat > "$LITELLM_CONFIG" <<EOF
model_list:
  - model_name: codex-bridge
    litellm_params:
      model: minimax/${BRIDGE_MODEL}
      api_key: os.environ/MINIMAX_API_KEY
      api_base: https://api.minimax.io/v1
EOF
    ;;
  *)
    echo "[codex_bridge] FATAL: unknown provider ${BRIDGE_PROVIDER}" >&2
    exit 1
    ;;
esac

# ---- 2. start litellm in background ---------------------------------
LITELLM_PORT="${LITELLM_PORT:-4000}"
LITELLM_LOG="${LITELLM_LOG:-/tmp/litellm-codex.log}"

if ! command -v litellm >/dev/null 2>&1; then
  echo "[codex_bridge] FATAL: litellm not installed. Add 'litellm[proxy]' to requirements.txt." >&2
  exit 1
fi

litellm --config "$LITELLM_CONFIG" --port "$LITELLM_PORT" --host 127.0.0.1 \
  > "$LITELLM_LOG" 2>&1 &
LITELLM_PID=$!
echo "[codex_bridge] litellm pid=${LITELLM_PID} log=${LITELLM_LOG}"

# Wait up to 30s for /health to come up. LiteLLM's first-boot import
# cost (loading provider modules) is the slow part — ~5s on a warm
# image, longer on cold disk.
ready=0
for i in $(seq 1 30); do
  if curl -sf "http://127.0.0.1:${LITELLM_PORT}/health/liveliness" >/dev/null 2>&1; then
    ready=1
    break
  fi
  sleep 1
done

if [ "$ready" != "1" ]; then
  echo "[codex_bridge] FATAL: litellm did not come up on :${LITELLM_PORT} in 30s" >&2
  echo "[codex_bridge] tail of $LITELLM_LOG:" >&2
  tail -40 "$LITELLM_LOG" >&2 || true
  exit 1
fi
echo "[codex_bridge] litellm ready on http://127.0.0.1:${LITELLM_PORT}"

# ---- 3. codex config.toml -------------------------------------------
# Define a custom model_provider that points at our local LiteLLM.
# wire_api stays "responses" because that's the only variant codex
# 0.72 accepts; LiteLLM emits a Responses-shaped reply so codex never
# notices the translation. env_key is set but the value is a sentinel
# — LiteLLM doesn't validate inbound auth in the no-master-key default
# config, but codex requires the env_key field to be populated.
CODEX_HOME="${CODEX_HOME:-${HOME}/.codex}"
mkdir -p "$CODEX_HOME"
CONFIG_TOML="${CODEX_HOME}/config.toml"

cat > "$CONFIG_TOML" <<EOF
# Auto-generated by codex_bridge.sh — do not edit by hand. Regenerated
# on every boot; safe to overwrite.
model = "codex-bridge"
model_provider = "${BRIDGE_PROVIDER}-bridge"

[model_providers."${BRIDGE_PROVIDER}-bridge"]
name = "${BRIDGE_PROVIDER} via LiteLLM bridge"
base_url = "http://127.0.0.1:${LITELLM_PORT}/v1"
wire_api = "responses"
env_key = "OPENAI_API_KEY"
EOF
chown "$(stat -c %u "$CODEX_HOME"):$(stat -c %g "$CODEX_HOME")" "$CONFIG_TOML" 2>/dev/null || true
echo "[codex_bridge] wrote codex config: $CONFIG_TOML"

# Codex requires OPENAI_API_KEY env to be non-empty even when pointing
# at a non-OpenAI provider via custom model_providers. The litellm
# proxy doesn't validate it (no master_key configured), so any
# non-empty value works.
export OPENAI_API_KEY="${OPENAI_API_KEY:-sk-litellm-bridge-placeholder}"
