#!/usr/bin/env bash
# codex_minimax_config.sh — write the official MiniMax provider config
# into ~/.codex/config.toml when MINIMAX_API_KEY is set. Sourced by
# start.sh (Docker boot) and the bare-host install path so both get
# the same shape.
#
# Source: https://platform.minimax.io/docs/token-plan/codex-cli
#
# Codex 0.72's WireApi enum has TWO variants — `responses` and `chat`
# (verified against codex-rs/core/src/model_provider_info.rs at
# rust-v0.72.0). Earlier upstream config-reference docs claimed only
# `responses` was supported; that was incorrect. Direct chat/completions
# routing works without any proxy in the loop.
#
# When MINIMAX_API_KEY is missing this is a no-op so OpenAI-direct
# users see no behavior change.

set -euo pipefail

if [ -z "${MINIMAX_API_KEY:-}" ]; then
  echo "[codex-minimax] no MINIMAX_API_KEY — codex will use its default (OpenAI) provider"
  return 0 2>/dev/null || exit 0
fi

CODEX_HOME="${CODEX_HOME:-${HOME}/.codex}"
mkdir -p "$CODEX_HOME"
CONFIG_TOML="${CODEX_HOME}/config.toml"

# Defaults pulled from MiniMax's official Codex CLI config
# (https://platform.minimax.io/docs/token-plan/codex-cli). Operators
# can override the model via CODEX_MINIMAX_MODEL or the base_url via
# MINIMAX_API_BASE (mainland-China ingress is api.minimaxi.com/v1).
MODEL="${CODEX_MINIMAX_MODEL:-codex-MiniMax-M2.7}"
BASE_URL="${MINIMAX_API_BASE:-https://api.minimax.io/v1}"

cat > "$CONFIG_TOML" <<EOF
# Auto-generated by codex_minimax_config.sh — do not edit by hand;
# regenerated on every boot from MINIMAX_API_KEY / CODEX_MINIMAX_MODEL
# / MINIMAX_API_BASE env. Source: MiniMax docs (token-plan/codex-cli).
model = "${MODEL}"
model_provider = "minimax"

[model_providers.minimax]
name = "MiniMax Chat Completions API"
base_url = "${BASE_URL}"
env_key = "MINIMAX_API_KEY"
wire_api = "chat"
requires_openai_auth = false
request_max_retries = 4
stream_max_retries = 10
stream_idle_timeout_ms = 300000
EOF

# Inherit ownership from the codex home dir so the agent user (which
# runs molecule-runtime) can read it under gosu.
if command -v stat >/dev/null 2>&1; then
  owner=$(stat -c "%u:%g" "$CODEX_HOME" 2>/dev/null || echo "")
  if [ -n "$owner" ]; then
    chown "$owner" "$CONFIG_TOML" 2>/dev/null || true
  fi
fi

echo "[codex-minimax] wrote ${CONFIG_TOML} model=${MODEL} provider=minimax"
