#!/usr/bin/env bash
# codex_minimax_config.sh — write the official MiniMax provider config
# into ~/.codex/config.toml when MINIMAX_API_KEY is set. Sourced by
# start.sh (Docker boot) and the bare-host install path so both get
# the same shape.
#
# Source: https://platform.minimax.io/docs/token-plan/codex-cli
#
# Codex 0.72's WireApi enum has TWO variants — `responses` and `chat`
# (verified against codex-rs/core/src/model_provider_info.rs at
# rust-v0.72.0). Earlier upstream config-reference docs claimed only
# `responses` was supported; that was incorrect. Direct chat/completions
# routing works without any proxy in the loop.
#
# When MINIMAX_API_KEY is missing this is a no-op so OpenAI-direct
# users see no behavior change.

set -euo pipefail

if [ -z "${MINIMAX_API_KEY:-}" ]; then
  echo "[codex-minimax] no MINIMAX_API_KEY — codex will use its default (OpenAI) provider"
  return 0 2>/dev/null || exit 0
fi

CODEX_HOME="${CODEX_HOME:-${HOME}/.codex}"
mkdir -p "$CODEX_HOME"
CONFIG_TOML="${CODEX_HOME}/config.toml"

# Defaults pulled from MiniMax's official Codex CLI config
# (https://platform.minimax.io/docs/token-plan/codex-cli). Operators
# can override the model via CODEX_MINIMAX_MODEL or the base_url via
# MINIMAX_API_BASE (mainland-China ingress is api.minimaxi.com/v1).
MODEL="${CODEX_MINIMAX_MODEL:-codex-MiniMax-M2.7}"
BASE_URL="${MINIMAX_API_BASE:-https://api.minimax.io/v1}"

cat > "$CONFIG_TOML" <<EOF
# Auto-generated by codex_minimax_config.sh — do not edit by hand;
# regenerated on every boot from MINIMAX_API_KEY / CODEX_MINIMAX_MODEL
# / MINIMAX_API_BASE env. Source: MiniMax docs (token-plan/codex-cli).
model = "${MODEL}"
model_provider = "minimax"

[model_providers.minimax]
name = "MiniMax Chat Completions API"
base_url = "${BASE_URL}"
env_key = "MINIMAX_API_KEY"
wire_api = "chat"
requires_openai_auth = false
request_max_retries = 4
stream_max_retries = 10
stream_idle_timeout_ms = 300000
EOF

# Inherit ownership from the codex home dir so the agent user (which
# runs molecule-runtime) can read it under gosu.
if command -v stat >/dev/null 2>&1; then
  owner=$(stat -c "%u:%g" "$CODEX_HOME" 2>/dev/null || echo "")
  if [ -n "$owner" ]; then
    chown "$owner" "$CONFIG_TOML" 2>/dev/null || true
  fi
fi

echo "[codex-minimax] wrote ${CONFIG_TOML} model=${MODEL} provider=minimax"

# Also patch /configs/config.yaml so molecule-runtime's load_config()
# passes ${MODEL} to executor.py instead of the library default
# (anthropic:claude-opus-4-7), which codex CLI rejects with
# `unknown model 'anthropic:claude-opus-4-7' (2013)` and hangs the
# first turn until task_complete that never arrives. Caught live on
# the 4-runtime A2A E2E (2026-05-03): codex executor took the turn
# lock, called turn/start with the wrong model, and never released
# — every subsequent A2A request piled up in the workspace-server
# queue as "busy".
#
# The provisioner has a MODEL_PROVIDER pass-through (ec2.go:1923) but
# never exports it from user-data, so the only path for a runtime to
# get the right model is to patch config.yaml from the install-time
# context that knows about MINIMAX_API_KEY.
WORKSPACE_CONFIG_DIR="${WORKSPACE_CONFIG_PATH:-/configs}"
WORKSPACE_CONFIG="${WORKSPACE_CONFIG_DIR}/config.yaml"
if [ -f "$WORKSPACE_CONFIG" ] && [ -w "$WORKSPACE_CONFIG_DIR" ]; then
  if grep -qE '^model:' "$WORKSPACE_CONFIG"; then
    sed -i.bak "s|^model: .*|model: '${MODEL}'|" "$WORKSPACE_CONFIG" && rm -f "${WORKSPACE_CONFIG}.bak"
  else
    printf "model: '%s'\n" "$MODEL" >> "$WORKSPACE_CONFIG"
  fi
  echo "[codex-minimax] patched ${WORKSPACE_CONFIG} model=${MODEL}"
elif [ -f "$WORKSPACE_CONFIG" ]; then
  # Read-only mount or wrong owner — log so operators can debug
  # rather than silently shipping the wrong default model.
  echo "[codex-minimax] WARN: ${WORKSPACE_CONFIG} exists but ${WORKSPACE_CONFIG_DIR} not writable; runtime will use default model" >&2
fi
